### ISSUE TITLE
Make the readme file much more cooler

### ISSUE THREAD

**Issue by PGautam27** [PGautam27/Morty_app#2]

**Comment by ayushtiwari110** [comment]
hello, i can work on this. kindly tell by cool means what i can help editing in that

**Comment by ShishuSidharth** [comment]
please assign this to me

**Comment by PGautam27** [comment]
I need you guys to brief out what the application is in the readme. And funky things about mortie and rick. And a perfect nice look on the readme. I'll attach a repo link, don't replicate it just take inspirations and enhance the readme file.
https://github.com/metafy-social/daily-python-scripts

@ayushtiwari110 you are assigned

**Comment by ayushtiwari110** [comment]
thanks for assigning. I will start working on it now.

**Comment by PGautam27** [comment]
Get the theme of rick and morty feel in it

**Comment by ayushtiwari110** [comment]
hello , i have made the readme more cool, kindly have a look at PR. if everything seems fine, kinly accept it and tag hacktoberfest accepted
